### ISSUE TITLE
窗口显示不完整

### ISSUE THREAD

**Issue by KawausoJyou** [Nigh/I-wanna-clean-keyboard#17]
![image](https://github.com/Nigh/I-wanna-clean-keyboard/assets/92703641/139ef043-fea7-4c73-bd15-ac8c95e5e4a2)
而且无法拖拽改变窗口大小。
![image](https://github.com/Nigh/I-wanna-clean-keyboard/assets/92703641/290238ab-9fda-43ee-b50a-0ca464a6b662)
![image](https://github.com/Nigh/I-wanna-clean-keyboard/assets/92703641/2476ec49-093f-47bc-90aa-edfc51c49ed4)

**Comment by Nigh** [comment]
应该是DPI缩放相关的问题。

**Comment by Nigh** [comment]
> 最新版与之前一样也显示不全XD（又不是不能用（无所谓（只是本着反馈问题的想法😂

@KawausoJyou 这样的话，虽然有点麻烦，大概还是得做一下DPI适配才行。

**Comment by Nigh** [comment]
@KawausoJyou 喜讯，DPI适配已经加上了
