### ISSUE TITLE
Suggest disabling DPI scaling

### ISSUE THREAD

**Issue by buaawjw** [Nigh/I-wanna-clean-keyboard#2]
It does not work well, at least with non-integer scale factors such as 125% or 150%. 

![screenshot](https://cloud.githubusercontent.com/assets/12931565/25166579/a292e514-250e-11e7-8727-f5399ebe4b7f.png)

According to [docs](https://autohotkey.com/docs/commands/Gui.htm), it can be disabled via
```
-Gui, -Caption +AlwaysOnTop +hwndGui1 -Owner
+Gui, -Caption +AlwaysOnTop +hwndGui1 -Owner -DPIScale
```

**Comment by Nigh** [comment]
thanks for your suggestion, dpi scale is disabled now.
