### ISSUE TITLE
未屏蔽的按键

### ISSUE THREAD

**Issue by AlekzKane-Illusion** [Nigh/I-wanna-clean-keyboard#24]
最新版小键盘Num、ctrl、alt、shift、scroll，依然能用。alt能用的表现是窗口菜单会因为按alt而显示，Num键的表现自然是会有光亮，ctrl和shift能用的表现是我设置的切换输入法快捷键是这个，scroll会亮（或者你打开个excel试试就知道），所以知道还能用。
另外Fn+功能键，也是能用的；ctrl+alt+del 也可以，但这个不知道能不能屏蔽，不了解原理，但个人感觉这个优先级应该非常高。
以上仅供建议参考。

**Comment by gaoyu19920914** [comment]
+1, 至少右侧 Alt 仍然没有被屏蔽，Windows 11 下的 Firefox 窗口菜单栏会跳出来。

**Comment by hrflni** [comment]
是的，我也发现了。
而且是只能屏蔽在桌面按键。
例如打开系统软件，所有按键是可以正常操作的。
事件查看器，系统，计算机管理之类。

**Comment by Nigh** [comment]
@hrflni 
> 是的，我也发现了。 而且是只能屏蔽在桌面按键。 例如打开系统软件，所有按键是可以正常操作的。 事件查看器，系统，计算机管理之类。

低权限的应用注册的全局热键无法在高权限应用中生效。可以尝试使用管理员权限启动`iwck`
