### ISSUE TITLE
屏蔽问题

### ISSUE THREAD

**Issue by 2085886325** [Nigh/I-wanna-clean-keyboard#27]
感谢开发者，我只是想屏蔽掉笔记本的键盘，没想到给我外接的键盘也给屏蔽了哈哈，不知道能不能只屏蔽笔记本的和添加一个自启动功能

**Comment by Nigh** [comment]
@2085886325 这个功能需要修改驱动文件才能实现。

**Comment by hrflni** [comment]
这么有趣么，那能不能把键盘定义为蓝牙键盘，然后关闭开关，那键盘就没有影响了。
