### ISSUE TITLE
Show software version on screen

### ISSUE THREAD

**Issue by simonguoxm** [Nigh/I-wanna-clean-keyboard#32]
Without software version , it is relatively hard to decide if you need to upgrade.

**Comment by shuaaaaaaaaaaaa** [comment]
> Without software version , it is relatively hard to decide if you need to upgrade.

You can see the version in the properties
![image](https://github.com/Nigh/I-wanna-clean-keyboard/assets/63639676/448a4787-abf5-4460-b299-973a554e1dae)

**Comment by Nigh** [comment]
solved in #33.
