### ISSUE TITLE
报错怎么办

### ISSUE THREAD

**Issue by AlexanderDash** [Nigh/I-wanna-clean-keyboard#37]
Error: This value of type "HTMLWindow2" has no property named "ahk".

▶	487: wb.document.parentWindow.ahk := NeutronWindow._Dispatch(this.parent)

The current thread will exit.

Call stack:
*#1 (487) : [NeutronWindow._WBEvents.Prototype.DocumentComplete] wb.document.parentWindow.ahk := NeutronWindow._Dispatch(this.parent)
*#1 (353) : [Sleep] Sleep(50)
*#1 (353) : [NeutronWindow.Prototype.Load] Sleep(50)
*#1 (513) : [] neutron := NeutronWindow().Load(path) .Opt("-Resize") .OnEvent("Close", (neutron) => ExitApp()) .Show("w" winW " h" winH, "iwck")
> Auto-execute

Error: This value of type "HTMLWindow2" has no property named "ahk".

▶	355: this.wnd.ahk := NeutronWindow._Dispatch(this)

Call stack:
*#1 (355) : [NeutronWindow.Prototype.Load] this.wnd.ahk := NeutronWindow._Dispatch(this)
*#1 (513) : [] neutron := NeutronWindow().Load(path) .Opt("-Resize") .OnEvent("Close", (neutron) => ExitApp()) .Show("w" winW " h" winH, "iwck")
> Auto-execute

![image](https://github.com/Nigh/I-wanna-clean-keyboard/assets/134115886/ce1ce823-b9ef-4ae5-9edd-5b795c35ae21)

三个怎么办。。

**Comment by Nigh** [comment]
@AlexanderDash  可能你的系统不含有程序运行必须的webview组件。

可以在如下地址下载后手动安装：
https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer

**Comment by Nigh** [comment]
Closed because of long periods of inactivity.
