### ISSUE TITLE
你好，希望添加一个收起页面的按钮

### ISSUE THREAD

**Issue by Benjamin-Watson0** [Nigh/I-wanna-clean-keyboard#6]
就像这个
![图片](https://user-images.githubusercontent.com/112467275/187824135-4ed3d94e-cdeb-4fde-aed1-00d72a476794.png)

十分感谢你的软件，帮了我大忙。

**Comment by Nigh** [comment]
最小化么？

**Comment by Benjamin-Watson0** [comment]
> 最小化么？

是的

**Comment by Nigh** [comment]
最小化后，没有任务栏图标，如何恢复？

**Comment by Benjamin-Watson0** [comment]
![图片](https://user-images.githubusercontent.com/112467275/188083022-2cd55b79-0090-4830-9ff9-322e5f17b9db.png)
任务栏是有的。
是不是咱两沟通有误会？是这样的，我想看网课，然后在键盘位置做笔记，用这个软件我就不用担心键盘误触问题了，就是屏幕上有这个应用的小窗口很碍眼，不过刚才试了下，全屏状态下是看不见窗口的。

**Comment by Nigh** [comment]
可以加一个折叠的状态。因为我不希望有用户因为误操作隐藏了窗口之后没法恢复键盘被屏蔽的状态。

**Comment by Benjamin-Watson0** [comment]
嗯嗯，总之就是上面的那个意思。谢谢你的解答了

**Comment by Nigh** [comment]
鉴于现在ahk的gdip库最新只支持到alpha版本，本项目将在gdip库更新至支持beta版本后同步更新。

**Comment by Nigh** [comment]
@Benjamin-Watson0  最新版本已经取消强制置顶特性。不会再遮挡前台窗口了。
