### ISSUE TITLE
无法运行，抛出异常

### ISSUE THREAD

**Issue by amorphobia** [Nigh/I-wanna-clean-keyboard#7]
打开遇到错误

```
---------------------------
iwck.exe
---------------------------
Error:  An exception was thrown.

Specifically: 0xc0000005

	Line#
--->	955: Return DllCall("gdiplus\GdipDeleteBrush", A_PtrSize ? "UPtr" : "UInt", pBrush)

The current thread will exit.
---------------------------
确定   
---------------------------
```

**Comment by Nigh** [comment]
先 `sfc /scannow` 修复下试试吧。

**Comment by amorphobia** [comment]
Sorry, 我补充一些新的信息，我是从 release 里下载的，[iwck_U64.exe](https://github.com/Nigh/I-wanna-clean-keyboard/releases/download/v2.0/iwck_U64.exe) 会遇到这个问题，但今天我试了试 [iwck_U32.exe](https://github.com/Nigh/I-wanna-clean-keyboard/releases/download/v2.0/iwck_U32.exe) 就没有问题。

另外，直接下载仓库里的 [iwck.exe](https://github.com/Nigh/I-wanna-clean-keyboard/blob/master/iwck.exe) 也是能运行的

所以可能只需要重新发布一个 release，或者加个说明就好了

**Comment by Nigh** [comment]
那我暂时移除`Unicode64`的release好了。

鉴于现在ahk的gdip库最新只支持到alpha版本，本项目将在gdip库更新至支持beta版本后同步更新。
