### ISSUE TITLE
可以添加白名单功能吗

### ISSUE THREAD

**Issue by 2584191127** [Nigh/I-wanna-clean-keyboard#8]
就是在白名单里的按键不被锁定可以正常使用

**Comment by Nigh** [comment]
@2584191127 具体需求的使用场景是怎样的？白名单功能不在iwck的开发计划中，如果确实有实用的场景需求，我会考虑开发新的软件来实现。

**Comment by 2584191127** [comment]
> @2584191127 具体需求的使用场景是怎样的？白名单功能不在iwck的开发计划中，如果确实有实用的场景需求，我会考虑开发新的软件来实现。

就是用电脑一边看网课一边记笔记，因为桌子小所以需要在键盘上写，然后就想把方向键加入白名单，这样又不会误触又能快进视频

**Comment by Nigh** [comment]
> 就是用电脑一边看网课一边记笔记，因为桌子小所以需要在键盘上写，然后就想把方向键加入白名单，这样又不会误触又能快进视频

安排了。

**Comment by Nigh** [comment]
AHKv2.0.2未提供类似API控制，现有API可以做到仅屏蔽可打印字符输入。
